# WAV HANDLING
DEFAULT_SAMPLE_RATE = 44100
DEFAULT_WINDOW = 2048
DEFAULT_HOP = 512

ORIG_WIDTH = 1025
ORIG_HEIGHT = 173

# DATASET AND MODEL HANDLING
BATCH_SIZE = 8
EPOCHS = 25
PATIENCE = 5
DEFAULT_MODEL = "bass_separator_25e.h5"

# INPUT/OUTPUT LAYERS
INPUT_WIDTH = 1040 # 1025
INPUT_HEIGHT = 176 # 173
INPUT_CHANNELS = 1
OUTPUT_CHANNELS = 2

# PATHS
PATH_TO_STEMS = r".\dataset\stems"
PATH_TO_WAV = r".\dataset\wav"
PATH_TO_NPY = r".\dataset\npy"
PATH_TO_MODEL = "./model"
PATH_TO_LOGS = "./logs/fit"
